name       : netperf
version    : 2.7.0
release    : 1
source     :
    - ftp://ftp.netperf.org/netperf/netperf-2.7.0.tar.gz : 9170c4758463bc5342dcdbfc88a40b586fcc9d7ccca048ecbb3b2d49387a28b9
license    : Distributable
component  : network.utils
summary    : Netperf is a benchmark that can be used to measure the performance of many different types of networking
description: |
    Netperf is a benchmark that can be used to measure the performance of many different types of networking
builddeps  :
    - gcc
setup      : |
    %configure --enable-unixdomain \
               --enable-dccp \
               --enable-sctp
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 COPYING $installdir/usr/share/doc/netperf/copyright
